#!/bin/bash
#
# USB Driveby Defender
#
#
#---------------------

#expect 4 arguments  
ARGS=4
# exit code 65 data format error
ERR_CODE=65
MYSQL=`which mysql`
echo "test" $# $1 $2 $3 $4
  
CDB="CREATE DATABASE IF NOT EXISTS $2;"
GU1="GRANT USAGE ON $2.* TO $3@$1 IDENTIFIED BY '$4';"
GU2="GRANT ALL PRIVILEGES ON $2.* TO $3@$1;"
FPS="FLUSH PRIVILEGES;"
VFY="SHOW DATABASES;"
UDB="USE $2;"
CWT="CREATE TABLE IF NOT EXISTS whitelist (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idvendor VARCHAR(4),
    idproduct VARCHAR(4),
    name VARCHAR(30)
    );"
IWT="INSERT INTO whitelist (idvendor,idproduct,name) 
     VALUES ('8644', '800e', 'Intenso GmbG');"
CBK="CREATE TABLE IF NOT EXISTS blacklist (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idvendor VARCHAR(4),
    idproduct VARCHAR(4),
    name VARCHAR(30)
    );"
IBK="INSERT INTO blacklist (idvendor,idproduct,name) 
     VALUES ('0718', '070a', 'Imation Corp'),
     ('413c','2003','Dell Computer Corp. Keyboard');"
SQL="${CDB}${GU1}${GU2}${FPS}${VFY}${UDB}${CWT}${IWT}${CBK}${IBK}"

#check if all arguments are satisfied  
if [ $# -ne $ARGS ]
then
  echo "Usage: $0 dbhost dbname dbuser dbpass"
  exit $ERR_CODE
fi
  
$MYSQL -uroot -p -e "$SQL"
