#!/bin/bash 
#
#Application:   USB Driveby Defender
#Authors:       Shea O'Neill, Paddy Cronan
#Date:          20/03/17
#Version:       1.0
#Title:         dbsetup
#Description:   This script creates the database
#-------------------------------------------------------------------------

#expect 4 arguments  
ARGS=4
# exit code 65 data format error
ERR_CODE=65
MYSQL=`which mysql`
echo "Arguments supplied:" $# $1 $2 $3 $4
  
CTDB="CREATE DATABASE $2;"
GUSG="GRANT USAGE ON $2.* TO $3@$1 IDENTIFIED BY '$4';"
GPLV="GRANT ALL PRIVILEGES ON $2.* TO $3@$1;"
FPLV="FLUSH PRIVILEGES;"
VRFY="SHOW DATABASES;"
UDB="USE $2;"
USRT="CREATE TABLE IF NOT EXISTS user (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(10),
    password VARCHAR(255),
    email VARCHAR(30)
    );"
#IUSRT="INSERT INTO user (username,password,email) 
    # VALUES ('${uname}', '${hashpass}, '${uemail}');"
BLKT="CREATE TABLE IF NOT EXISTS blacklist (
    device_id INT AUTO_INCREMENT PRIMARY KEY,
    vendor_id VARCHAR(4),
    product_id VARCHAR(4),
    device_type VARCHAR(30)
    );"
#IBLKT="INSERT INTO blacklist (vendor_id,product_id,device_type) 
     #VALUES ('0718', '070a', 'Imation Corp'),
     #('413c','2003','Dell Computer Corp. Keyboard');"
ATKLG="CREATE TABLE IF NOT EXISTS attack_log (
    attack_id INT AUTO_INCREMENT PRIMARY KEY,
    device_id INT, 
    FOREIGN KEY (device_id)
        REFERENCES blacklist(device_id)
        ON DELETE CASCADE,
    user_id INT,
    FOREIGN KEY (user_id)
        REFERENCES user(user_id)
        ON DELETE CASCADE,
    time DATETIME NOT NULL DEFAULT NOW()
    );"

SQL="${CTDB}${GUSG}${GPLV}${FPLV}${VRFY}${UDB}${USRT}${BLKT}${ATKLG}"

#check if all arguments are satisfied  
if [ $# -ne $ARGS ]
then
  echo "Usage: $0 dbhost dbname dbuser dbpass"
  exit $ERR_CODE
fi
  
$MYSQL -uroot -p -e "$SQL"
